feat/building the coin listing screen
ozielguimaraes/take-my-money pull request #4
Opened 2022-05-23 15:21 UTC by Hedipo-Duarte-Oliveira

feat/building the coin listing screen

2022-05-23 15:22 UTC, Andressa-dSSouza approved these changes

2022-05-23 16:44 UTC, ozielguimaraes requested changes

2022-05-23 16:44 UTC, ozielguimaraes commented on app/src/main/res/values/strings.xml
> +    <string name="Btc">btc</string>
Strings name should be all lower_case
Nomes de string deveria ser todas em minúsculas

2022-05-23 16:44 UTC, ozielguimaraes commented on app/src/main/res/layout/coins_details.xml
> +        android:text="@string/bitcoin"
Quando um determinado texto for ser substituido por outro valor via Activity, fragment, adapter, viewHolder... Não há necessidade de criar uma string com o texto
`android:text` pode/deve ser substituido por `tools:text`

Você  precisa adicionar esse namespace no header do arquivo
`xmlns:tools="http://schemas.android.com/tools"`

2022-05-23 17:48 UTC, WesleyVilaNova approved these changes

2022-05-24 14:18 UTC, ozielguimaraes approved these changes

2022-05-24 14:18 UTC, merged